name: Python Lint

on:
  push:
    # paths:
    #  - "**.py"
  pull_request:
    # paths:
    #   - "**.py"

jobs:
  Lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          
      - name: Run pylint
        run: |
          pylint $(find . -name "*.py")