name: Python Lint

on:
  push:
    # paths:
    #  - "**.py"
  pull_request:
    # paths:
    #   - "**.py"

jobs:
  Lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
        
      - name: Python Linter (mypy, pylint, black, isort)
        uses: sunnysid3up/python-linter@master
        with:
          source: "."
          mypy-options: "--show-error-codes"
          pylint-options: "--recursive"
          isort-options: "-w 100"
          django: false
